global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'restaurant-service'
    static_configs:
      - targets: ['restaurant-service:8082']

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8083']

  - job_name: 'spider-service'
    static_configs:
      - targets: ['spider-service:8084']

  - job_name: 'mail-service'
    static_configs:
      - targets: ['mail-service:8085']

  - job_name: 'map-service'
    static_configs:
      - targets: ['map-service:8086']
